SELECT description, runs, batting_data.balls, minutes, sixes, strike_rate, batting_position, player.player_name, weather.temp, weather.feels, weather.gust, weather.wind, weather.rain, weather.humidity, weather.cloud, weather.pressure, weather.viscosity, match_details.inning, match_details.result,match_details.batting_session, match_details.toss, venue.venue_name, opposition.opposition_name, season.id as season_id FROM `batting_data` left join player on player_id=player.id left join (select * from weather_data WHERE SESSION like "batting") as weather on batting_data.match_id=weather.match_id left join match_details on match_details.match_id=weather.match_id left join venue on venue.id= match_details.venue_id left join opposition on opposition.id=match_details.opposition_id left join season on season.id=match_details.season_id


SELECT description, runs, batting_data.balls, minutes, sixes, strike_rate, batting_position, player.player_name, weather.temp, weather.feels, weather.gust, weather.wind, weather.rain, weather.humidity, weather.cloud, weather.pressure, weather.viscosity, match_details.inning, match_details.result,match_details.batting_session, match_details.toss, venue.venue_name, opposition.opposition_name, season.id as season_id FROM `batting_data` left join player on player_id=player.id left join (select * from weather_data WHERE SESSION like "batting") as weather on batting_data.match_id=weather.match_id left join match_details on match_details.match_id=weather.match_id left join venue on venue.id= match_details.venue_id left join opposition on opposition.id=match_details.opposition_id left join season on season.id=match_details.season_id where player_id = 1

SELECT player_name,AVG(runs) as average, weather_data.temp FROM `batting_data` left join player on player_id=player.id left join weather_data on weather_data.match_id=batting_data.match_id group by weather_data.temp, player.player_name

SELECT bowling_data.balls, maidens, runs, bowling_data.wickets, dots, fours, sixes, econ, wides, no_balls, player.player_name, weather.temp, weather.feels, weather.gust, weather.wind, weather.rain, weather.humidity, weather.cloud, weather.pressure, weather.viscosity, match_details.inning, match_details.result,match_details.bowling_session, match_details.toss, venue.venue_name, opposition.opposition_name, season.id as season_id 
FROM `bowling_data` left join player on player_id=player.id left join (select * from weather_data WHERE SESSION like "bowling") as weather on bowling_data.match_id=weather.match_id left join match_details on match_details.match_id=weather.match_id left join venue on venue.id= match_details.venue_id left join opposition on opposition.id=match_details.opposition_id left join season on season.id=match_details.season_id


SELECT player_name,COUNT(*) as count FROM `batting_data` left join player on player_id=player.id group by player_name ORDER BY COUNT DESC 
